apiVersion: v1 
kind : Service 
metadata : 
  name : house-price-prediction-service
spec:
  type: LoadBalancer
  selector:
    app : house-price-prediction-app
  ports: 
    - port: 80
      targetPort: 8080